### ISSUE TITLE
Session 1 Checklist

### ISSUE THREAD

**Issue by Web-learning** [Web-learning/Open-Umbrella#4]
### The on-boarding session 

1. Session Preparation [LEAD]
- [ ] Insert outcomes, identify presentation or speakers
- [ ] Make a copy of the [session template](https://github.com/Web-learning/Open-Umbrella/tree/main/session-01)
- [ ]  Prepare the etherpad notepad
- [ ]  Send etherpad to the Host
- [ ]  Other
2. Call Preparation [LEAD and Host]
- [ ] Review outcomes and speakers
- [ ] Approve weekly etherpad

3. Weekly comms a day before

4. WhatsApp comms 10 minutes before
